name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23licNFfFKePSbcQXu"
GITHUB_OWNER = "aivrz"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://i6f.cn/api/auth"
NEXT_PUBLIC_API_URL="https://i6f.cn"

# 👇 添加这些用于加速构建
NODE_VERSION = "22.16.0"
PNPM_VERSION = "10.11.1"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
# 强制使用缓存
PNPM_STORE_PATH = "/opt/buildhome/.pnpm-store"
NEXT_TELEMETRY_DISABLED = "1"
# 新增：跳过 Vercel 的重复安装
VERCEL_SKIP_PNPM_INSTALL = "true"   
NEXT_TELEMETRY_DISABLED = "1"
